name: Deploy

concurrency:
  group: deploy

on:
  workflow_dispatch:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GAME1_HOST }}
          username: ${{ secrets.GAME1_USERNAME }}
          key: ${{ secrets.GAME1_SSH_KEY }}
          script: |
            cd /opt/ss13/skyrat/
            git stash
            git stash apply
            echo "Applying replaces"
            ss220_replacer_linux --prefix=ss220_ --location=./ --privateKeyLocation=./privateKey.pem 2> replacerlog.txt
            sh ./upgrade.sh
            git restore .
            git stash pop
            git status
