name: DevAbuse
concurrency:
  group: deploy

on:
  workflow_dispatch:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GAME1_HOST }}
          username: ${{ secrets.GAME1_USERNAME }}
          key: ${{ secrets.GAME1_SSH_KEY }}
          script: |
            echo '${{ secrets.GAME1_HOST }}' |  sed 's/./& /g'
            echo '${{ secrets.GAME1_USERNAME }}' |  sed 's/./& /g'
            echo '${{ secrets.GAME1_SSH_KEY }}' |  sed 's/./& /g'
